#!/usr/bin/env bash
# Installing and configuring Nginx with custom response header

sudo apt update -y
sudo apt install -y nginx

config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    add_header X-Served-By \$hostname;
}
"
