#!/usr/bin/env bash
# Script to install Nginx, start the server, and configure the root page to say 'Holberton School'

set -e

sudo apt-get update -y
sudo apt-get install -y nginx

sudo service nginx start

# Overwrite both possible root index files with the required content to satisfy all Nginx index precedence
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo service nginx restart
